[window]
dimensions =  { columns = 0, lines = 0 }
position = "None" # "None" | { x = 0, y = 0 }
padding = { x = 8, y = 8 }
dynamic_padding = false
decorations = "Full" # "Full" | "None" | "Transparent" (Macos only) | "Buttonless" (Macos only)
opacity = 0.9
blur = false 
startup_mode = "Windowed" # "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen" (Macos only)
title = "Alacritty"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" } # (Linux/BSD only)
decorations_theme_variant = "None" # "Dark" | "Light" | "None"
resize_increments = false
option_as_alt = "None" # "OnlyLeft" | "OnlyRight" | "Both" | "None" # (macos only)

[font]
normal = { family = "CodeNewRoman Nerd Font Mono", style = "Italic" }
bold = { family = "CodeNewRoman Nerd Font Mono", style = "Bold" }
italic = { family = "CodeNewRoman Nerd Font Mono", style = "Italic" }
bold_italic = { family = "CodeNewRoman Nerd Font Mono", style = "Bold Italic" }
size = 14
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true

[cursor]
style = { shape = "Beam", blinking = "Off" }
# shape = "Block" | "Underline" | "Beam"
# Default: "Block"

# blinking = "Never" | "Off" | "On" | "Always"
# Never - Prevent the cursor from ever blinking
# Off - Disable blinking by default
# On - Enable blinking by default
# Always -Force the cursor to always blink
# Default: "Off"
vi_mode_style = "None" # { <shape>, <blinking> } | "None"
blink_interval = 750
blink_timeout = 5
unfocused_hollow = true
thickness = 0.15

