[manager]
prepend_keymap = [
  # Navigation
  { on  = [ "K" ],        run = "plugin --sync parent-arrow --args=-1", desc = "Move parent cursor up"},
  { on  = [ "J" ],        run = "plugin --sync parent-arrow --args=1",  desc = "Move parent cursor down"},
  { on = [ "l" ],         run = "plugin --sync smart-enter",            desc = "Enter the child directory, or open the file" },
  { on = [ "p" ],         run = "plugin --sync smart-paste",            desc = "Paste into the hovered directory or CWD" },
	{ on = [ "d" ],         run = "remove --force",                       desc = "Move the files to the trash" },
	{ on = [ "D" ],         run = "remove --permanently --force",         desc = "Permanently delete the files" },
  { on = [ "r" ],         run = "rename --cursor=start --empty=stem",   desc = "Rename a file or directory" },
]

[input]
prepend_keymap = [
  { on   = [ "<Esc>" ], run  = "close", desc = "Cancel input" },
]
