bold = true
color_mode = "ansi" # ansi, rgb or none
palette = "pastel" # default, darker, pastel or matrix
rainbow = 0 # 0-255
delay_ms = 30
inherit_style = true 
kinds = ["heavy"] # heavy, light, curved, knobby, emoji, outline, dots, blocks, sus
num_pipes = 5
reset_threshold = 0.9 # 0.0–1.0
turn_chance = 0.15 # 0.0–1.0
