#!/bin/sh

# Check which waybar theme is set
THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f2)

#if the theme is not dark then we need to switch to it
if [ $THEMEIS != "dark.css" ]; then
    SWITCHTO="-dark"
fi

#set the waybar theme
ln -sf ~/.config/waybar/style/style$SWITCHTO.css ~/.config/waybar/style.css

#set the wofi theme
ln -sf ~/.config/wofi/style/style$SWITCHTO.css ~/.config/wofi/style.css

# #set the xfce theme
# xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita$SWITCHTO"
# xfconf-query -c xsettings -p /Net/IconThemeName -s "Nordic-cursors"
#
#set the GTK theme
gsettings set org.gnome.desktop.interface gtk-theme "Everforest-Dark-BL"
gsettings set org.gnome.desktop.interface icon-theme "Tela-circle-nord-dark"

#change the background image and be cool about it ;)
if [ $THEMEIS == "dark.css" ]; then
  swww img --resize crop -o DP-2 $HOME/.config/hypr/background/102.jpg --transition-fps 60 --transition-type center --transition-duration 2
  swww img -o HDMI-A-1 $HOME/.config/hypr/background/009.png --transition-fps 60 --transition-type center --transition-duration 2
else
  swww img --resize crop -o DP-2  $HOME/.config/hypr/background/104.jpg --transition-fps 60 --transition-type center --transition-duration 2
  swww img  -o HDMI-A-1  $HOME/.config/hypr/background/009.png --transition-fps 60 --transition-type center --transition-duration 2
fi

#update the sddm image
#ln -sf /usr/share/sddm/themes/sdt/Backgrounds/wallpaper$SWITCHTO.jpg /usr/share/sddm/themes/sdt/wallpaper.jpg

#restart the waybar
killall -SIGUSR2 waybar
